<a href="https://colab.research.google.com/github/abidhussain49/First/blob/master/Q2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
rr=np.arange(1,37).reshape(6,6)

In [8]:
rr[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [0]:
rr2=np.arange(75).reshape(3,5,5)

In [10]:
rr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [13]:
rr2[0,::-1,::-1]

array([[24, 19, 14,  9,  4],
       [23, 18, 13,  8,  3],
       [22, 17, 12,  7,  2],
       [21, 16, 11,  6,  1],
       [20, 15, 10,  5,  0]])

In [15]:
rr2[1,:,1:3]

array([[26, 27],
       [31, 32],
       [36, 37],
       [41, 42],
       [46, 47]])

In [16]:
rr2[1,:,1:2]

array([[26],
       [31],
       [36],
       [41],
       [46]])